"""Deterministic M6 briefing queues and local preview."""

import hashlib
import json
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

from app.llm.core import Router


class BriefingItem(BaseModel):
    model_config = ConfigDict(extra="forbid")
    event_id: str
    title: str
    source_urls: list[str]
    importance: int = Field(ge=0, le=10)
    interest: int = Field(ge=0, le=10)
    global_importance: int = Field(ge=0, le=10)
    actionable: bool = False
    video: bool = False
    source_type: str = "rss"
    published_at: datetime | None = None
    why_watch: str | None = None
    connection: str | None = None
    # These are distilled at extraction time and persisted with the briefing.  They are
    # deliberately not generated by the reader page.
    summary_tr: str | None = None
    what_changed_tr: str | None = None
    why_important_tr: str | None = None


def build_sections(items: list[BriefingItem]) -> dict[str, list[BriefingItem]]:
    unique = {item.event_id: item for item in items}.values()
    ordered = sorted(unique, key=lambda item: item.importance, reverse=True)
    world = [item for item in ordered if item.global_importance >= 7][:7]
    return {
        "Action Required": [item for item in ordered if item.actionable],
        "For You": [item for item in ordered if item.interest >= 7 and not item.actionable],
        "Tech & Industry": [
            item
            for item in ordered
            if item.importance >= 5 and item not in world and not item.actionable
        ],
        "Connections / Why It Matters": [item for item in ordered if item.connection],
        "World in Brief": world,
        "Worth Watching": [item for item in ordered if item.video],
    }


def render_preview(sections: dict[str, list[BriefingItem]]) -> str:
    return "\n".join(
        f"{section}\n"
        + "\n".join(_render_item(item) for item in items)
        for section, items in sections.items()
        if items
    )


def _render_item(item: BriefingItem) -> str:
    details = [item.why_watch] if item.why_watch else []
    if item.published_at:
        details.append(f"Published: {item.published_at.isoformat()}")
    details.extend(item.source_urls)
    return f"- {item.title}: {', '.join(details)}"


class EditedBriefing(BaseModel):
    model_config = ConfigDict(extra="forbid")
    title: str
    summary: str


async def edit_compact(sections: dict[str, list[BriefingItem]], router: Router) -> EditedBriefing:
    """Edit only a bounded, distilled briefing; empty briefings never reach this boundary."""
    if not any(sections.values()):
        raise ValueError("an empty briefing must not call the editor")
    context = {
        name: [
            {
                "title": item.title[:320],
                "source_urls": [url[:300] for url in item.source_urls[:2]],
            }
            for item in items[:10]
        ]
        for name, items in sections.items()
    }
    prompt = json.dumps(context, ensure_ascii=False)[: router.input_char_limit("editor")]
    content_hash = hashlib.sha256(prompt.encode()).hexdigest()
    return await router.structured("editor", prompt, content_hash, EditedBriefing, "v2", "v1")
